---
general:
  buildTool: 'mta'

stages:
  Build:
    mavenExecuteStaticCodeChecks: false
    npmExecuteLint: true

  Additional Unit Tests:
    karmaExecuteTests: false

  Malware Scan: 
    malwareExecuteScan: true

  Acceptance:
    cloudFoundryDeploy: true                                               # true, if you want to deploy to Cloud Foundry test space (default: false)
    cfApiEndpoint: "https://api.cf.us10-001.hana.ondemand.com" 
    cfOrg: "96468441trial"
    cfSpace: "dev"                               
    cfCredentialsId: "cf"
    deployType: "standard"
    npmExecuteEndToEndTests: true                                          # true, if you want to execute end-to-end acceptance tests using WebdriverIO (default: false)

  Compliance:
      sonarExecuteScan: false 

  Release:
    cloudFoundryDeploy: true                                     # true, if you want to deploy to Cloud Foundry (default: false)
    cfApiEndpoint: "https://api.cf.us10-001.hana.ondemand.com"   # for example, https://api.cf.eu10.hana.ondemand.com
    cfOrg: "96468441trial"
    cfSpace: "dev"                             # enter the Cloud Foundry space, to which you want to deploy your application
    cfAppName: "gitproject"
    deployType: "standard"   
    cfCredentialsId: "cf"
    tmsUpload: true                                                           # true, if you want to upload your artifact to SAP Cloud Transport Management


steps:
  npmExecuteLint:
    failOnError: true

  mtaBuild:
    platform: 'CF'
  
  # cloudFoundryDeploy:
  #   deployTool: 'mtaDeployPlugin'
  #   deployType: 'standard'
  #   cloudFoundry:
  #     org: '<your-organisation>'
  #     space: '<your-space>'
  #     credentialsId: 'CF_CREDENTIALSID'

  cloudFoundryDeploy:                                                                      # only relevant, if you set the cloudFoundryDeploy parameter in the Release stage to true 
    mtaDeployParameters: "-f --version-rule ALL"

  tmsUpload:                                                                               # only relevant, if you set the tmsUpload parameter in the Release stage to true
    nodeName: "DEV"
    credentialsId: "tms-sk"
    customDescription: 'TMS Upload'
    

# tmsUpload:  # only relevant once you finish the SAP Cloud Transport Management Expert Scope chapter
#   nodeName: 'QA'
#   credentialsId: 'tms'
#   customDescription: 'TMS Upload'